### ISSUE TITLE
Adding severity for ruleset

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/grant#51]
Hi,

Might be a good idea to add a "severity" to each rule (default can be unknown).
can help users to prioritize licenses issues (like with CVEs).

```
rules: 
    - pattern: "*gpl*"
      name: "deny-gpl"
      mode: "deny"
      reason: "GPL licenses are not allowed per xxx-xx company policy"
      severity: "High"
      exclusions:
        - "alpine-base-layout" # We don't link against this package so we don't care about its license
```
